name: notify
on: [pull_request, pull_request_review, pull_request_review_comment, workflow_dispatch]
jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: convert event object to plain text
        id: convert
        run: echo "plaintext=(echo ${{ toJson(github.event) }} | jq -r toString)" >> $PLAIN_TEXT
        # run: echo '::set-output name=plaintext::$(echo "{{ toJson(github.event) }}" | jq -r toString}'
      - name: POST request
        run: |
           curl -X POST -H 'Content-Type: application/json' -d '{"type": "message","attachments": [{"contentType": "application/vnd.microsoft.card.adaptive","contentUrl": null,"content": {"type": "AdaptiveCard","body": [{"type": "TextBlock","text": "${{ $PLAIN_TEXT }}" \n予約投稿テスト","wrap": true}],"$schema": "http://adaptivecards.io/schemas/adaptive-card.json","version": "1.5"}}]}' ${{ secrets.URL}}
