name: notify
on: [pull_request_target, pull_request_review, pull_request_review_comment, workflow_dispatch]
jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: convert event object to plain text
        id: convert
        run: echo plaintext="${{ toJson(github.event) }}" | jq -r toString
