name: notify
run-name: ${{ github.workflow }} (${{ github.ref_name }}) [${{ github.event_name }}.${{ github.event.action }}]
on: [pull_request, pull_request_target, pull_request_review, pull_request_review_comment, workflow_dispatch]
jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull_request
        if: github.event_name == 'pull_request'
        run: echo pull_request



#      - name: convert event object to plain text
#        id: convert
#        run: echo plaintext="${{ toJson(github.event) }} | jq -r toString"
