name: notify
env:
  BRANCH_NAME: ${{ (github.head_ref && github.head_ref) || (github.ref_name && github.ref_name) }}
run-name: ${{ github.workflow }} (${{ (github.head_ref && github.head_ref) || (github.ref_name && github.ref_name)  }}) [${{ github.event_name }}.${{ github.event.action }}]
on:
  pull_request:
    types: 
      - opened
      - edited
      - closed
      - reopened
      - synchronize
  pull_request_target:
      types: 
      - opened
      - edited
      - closed
      - reopened
      - synchronize
  pull_request_review:
  pull_request_review_comment:
  workflow_dispatch:
  
jobs:
  post_request:
    runs-on: ubuntu-latest
    steps:
      - name: pull_request and not an article edit
        if: ${{ (github.event_name == 'pull_request') && contains( env.BRANCH_NAME , 'system/') }}
        run: echo "description=ウェブサイトのシステムの更新がリクエストされました" >> $GITHUB_ENV
      - name: pull_request and an article edit
        if: ${{ (github.event_name == 'pull_request') && contains( env.BRANCH_NAME , 'article/') }}
        run: echo "description=新規記事の投稿がリクエストされました" >> $GITHUB_ENV
      - name: pull_request and other
        if: ${{ (github.event_name == 'pull_request') && ( env.description )
        run: echo "description=更新がリクエストされました" >> $GITHUB_ENV

#      - name: convert event object to plain text
#        id: convert
#        run: echo plaintext="${{ toJson(github.event) }} | jq -r toString"
