name: notify
env:
  BRANCH_NAME: ${{ (github.head_ref && github.head_ref) || (github.ref_name && github.ref_name) }}
run-name: ${{ github.workflow }} (${{ (github.head_ref && github.head_ref) || (github.ref_name && github.ref_name)  }}) [${{ github.event_name }}.${{ github.event.action }}]
on:
  pull_request:
    types:
      - opened
      - edited
      - closed
      - reopened
      - synchronize
  # pull_request_target:
  #    types:
  #    - opened
  #    - edited
  #    - closed
  #    - reopened
  #    - synchronize
  pull_request_review:
  pull_request_review_comment:
  workflow_dispatch:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    outputs:
      pull_request_message_title: ${{ steps.message_title.outputs.pull_request_message_title }}
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - id: opened
        # pull requestが作成されたとき
        if: ${{ github.event.action == 'opened' }}
        run: echo "message_title=リクエストの追加" >> $GITHUB_ENV

      - id: edited-or-synchronize
        # pull requestが編集されたとき
        if: ${{ github.event.action == 'edited' || github.event.action == 'synchronize'}}
        run: echo "message_title=リクエストの編集" >> $GITHUB_ENV

      - id: merged
        # pull requestがcloseされ，かつmargeされたとき
        if: ${{ github.event.action == 'closed' || github.event.pull_request.merged }}
        run: echo "message_title=リクエストの承認・反映" >> $GITHUB_ENV

      - id: closed
        # pull requestがcloseされ，かつmargeされなかったとき
        if: ${{ github.event.action == 'closed' || github.event.pull_request.merged }}
        run: echo "message_title=リクエストの却下" >> $GITHUB_ENV

      - id: message_title
        run: echo "pull_request_message_title=${{ env.message_title }}" >> $GITHUB_OUTPUT

  return_message_title:
    # if: ${{ needs.pull_request.outputs.message_title }}
    runs-on: ubuntu-latest
    needs: pull_request
    steps:
      - run: echo ${{ needs.pull_request.outputs.pull_request_message_title }}

  #  if: ${{ github.event.action == 'opened' }}

  #   steps:
  #     - name: pull_request and system improvements
  #       if: ${{ github.event_name == 'pull_request' && contains( env.BRANCH_NAME , 'system/') }}
  #       run: echo "message_title=システムの更新がリクエストされました" >> $GITHUB_ENV
  #     - name: pull_request and an article edit
  #       if: ${{ github.event_name == 'pull_request' && contains( env.BRANCH_NAME , 'article/') }}
  #       run: echo "message_title=新規記事の投稿がリクエストされました" >> $GITHUB_ENV
  #     - name: pull_request and other
  #       if: ${{ github.event_name == 'pull_request' && !env.message_title }}
  #       run: echo "message_title=更新がリクエストされました" >> $GITHUB_ENV
  #     - name: return message_title
  #       run: echo "{message_title}=${{ env.message_title }}" >> $GITHUB_OUTPUT
