name: notify
on: [pull_request, pull_request_review, pull_request_review_comment]
jobs:
  post-request:
    runs-on: ubuntu-latest
    steps:
      - run: |
          | curl -X POST -H 'Content-Type: application/json' -d '{    "type": "AdaptiveCard",    "body": [        {            "type": "TextBlock",            "text": "${description}",            "wrap": true        }    ],    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",    "version": "1.5"}' -${URL}
